version: 0.2

phases:
  build:
    commands:
      - echo "Creating zip file of selected application files..."
      # Add or remove files and directories below as needed
      - zip -r app.py requirements.txt Procfile Dockerfile database/ static/ templates/

artifacts:
  files:
    - app.zip
